(use-package startup-conf)

(when (load "private-conf.el")
  (use-package private-conf))

(use-package buffer-move)
(use-package dockerfile-mode)
(use-package wgrep)
(use-package autocomplete-conf)
(use-package behavior-conf)
(use-package bindings-conf)
(use-package browser-conf)
(use-package counsel-conf)
(use-package dashboard-conf)
(use-package docs-conf)
(use-package epub-conf)
(use-package evil-conf)
(use-package functions-conf)
(use-package git-conf)
(use-package lang-conf)
(use-package merge-conf)
(use-package minibuffer-conf)
(use-package mode-conf)
(use-package org-conf)
(use-package package-conf)
(use-package pdf-conf)
(use-package project-conf)
(use-package scroll-conf)
(use-package search-conf)
(use-package service-conf)
(use-package snippet-conf)
(use-package style-conf)
(use-package theme-conf)
(use-package tractsoft-conf)
(use-package ui-conf)
(use-package wm-conf)
;; dired-conf
;; slack-conf


(provide 'config)
