(use-package all-the-icons-ivy-rich)
(use-package avy)
(use-package benchmark-init)
(use-package buffer-move)
(use-package cargo :defer t)
(use-package circe)
(use-package circe-notifications)
(use-package command-log-mode)
(use-package counsel)
(use-package counsel-projectile)
(use-package dash)
(use-package dash-functional)
(use-package define-word)
(use-package direnv)
(use-package docker :bind ("C-c d" . docker))
(use-package dockerfile-mode)
(use-package doom-modeline)
(use-package doom-themes)
(use-package dotenv-mode)
(use-package dumb-jump)
(use-package ein :defer t)
(use-package elixir-mode :defer t)
(use-package emacsql :defer t)
(use-package emacsql-psql :defer t)
(use-package emacsql-sqlite :defer t)
(use-package ess :defer t)
(use-package esup)
(use-package etymology-of-word)
(use-package evil)
(use-package evil-commentary)
(use-package evil-multiedit)
(use-package evil-surround)
(use-package evil-visualstar)
(use-package exec-path-from-shell)
(use-package explain-pause-mode)
(use-package f)
(use-package flycheck)
(use-package flycheck-popup-tip)
(use-package flycheck-rust :after (rust-mode))
(use-package general)
(use-package go-mode :defer t)
(use-package haskell-mode)
(use-package helm-dash)
(use-package hl-todo)
(use-package hlint-refactor :after (haskell-mode))
(use-package hydra)
(use-package ivy)
(use-package ivy-hydra)
(use-package ivy-xref)
(use-package js2-mode :defer t)
(use-package json-navigator)
(use-package lsp-haskell :after (lsp-mode haskell-mode))
(use-package lsp-ui :after (lsp-mode))
(use-package markdown-preview-eww)
(use-package markdown-preview-mode)
(use-package mediawiki)
(use-package nav-flash)
(use-package nov)
(use-package org-bullets)
(use-package paxedit)
(use-package prettier-js)
(use-package projectile)
(use-package projectile-direnv)
(use-package racer)
(use-package racket-mode :defer t)
(use-package rainbow-delimiters)
(use-package rainbow-identifiers)
(use-package rainbow-mode)
(use-package ranger)
(use-package restart-emacs)
(use-package rjsx-mode)
(use-package rust-mode :defer t)
(use-package s)
(use-package slime)
(use-package smex)
(use-package sqlup-mode)
(use-package tree-mode)
(use-package undo-tree)
(use-package uuid)
(use-package vega-view)
(use-package visual-fill-column)
(use-package web)
(use-package wgrep)
(use-package which-key)
(use-package yaml-mode :defer t)
(use-package yasnippet)
;; (use-package gnuplot)
;; (use-package gnuplot-mode)

(provide 'startup-conf)
