(require 'dockerfile-mode)
(require 'wgrep)

(require 'agda-conf)
(require 'autocomplete-conf)
(require 'bindings-conf)
(require 'c-conf)
(require 'counsel-conf)
(require 'docs-conf)
(require 'elisp-conf)
(require 'evil-conf)
(require 'functions-conf)
(require 'git-conf)
(require 'haskell-conf)
(require 'lisp-conf)
(require 'lsp-conf)
(require 'minibuffer-conf)
(require 'org-conf)
(require 'project-conf)
(require 'scroll-conf)
(require 'search-conf)
(require 'shell-conf)
(require 'style-conf)
(require 'theme-conf)
(require 'ui-conf)

(require 'modes)

(provide 'config)
