(require 'bindings-conf)
(require 'c-conf)
(require 'elisp-conf)
(require 'evil-conf)
(require 'functions-conf)
(require 'git-conf)
(require 'org-conf)
(require 'project-conf)
(require 'style-conf)
(require 'ui-conf)

(provide 'config)
