(menu-bar-mode -1)
(tool-bar-mode -1)
(scroll-bar-mode -1)
(column-number-mode)
(show-paren-mode)
(electric-pair-mode)
(global-linum-mode)
(global-auto-revert-mode)
(ivy-mode)
(evil-mode)
(rainbow-delimiters-mode)
(rainbow-identifiers-mode)
(load-theme 'doom-molokai t)

(provide 'ui-conf)
