(require 'config/theme)
(require 'config/search)
(require 'config/navigation)
(require 'config/text)
(require 'config/prog)
(require 'config/info)
(require 'config/desktop)
(require 'config/dev)
(require 'config/langs)
(require 'config/modes)
(require 'config/services)
(require 'config/viewers)
(require 'config/shah)
(require 'config/utils)

(provide 'config)
