(require 'core/bindings)
(require 'core/commands)
(require 'core/window_manager)
(require 'core/navigation)
(require 'core/theme)
(require 'core/debug)
(require 'core/env)
(require 'core/prog)

(provide 'core)
