(require 'core/bindings)
(require 'core/desktop)
(require 'core/search)
(require 'core/navigation)
(require 'core/theme)
(require 'core/info)
(require 'core/env)
(require 'core/text)
(require 'core/prog)

(provide 'core)
