(use-package alarm-clock)
(use-package cargo :defer t)
(use-package define-word)
(use-package docker :bind ("C-c d" . docker))
(use-package dotenv-mode)
(use-package elixir-mode :defer t)
(use-package emacsql :defer t)
(use-package emacsql-psql :defer t)
(use-package emacsql-sqlite :defer t)
(use-package etymology-of-word)
(use-package flycheck)
(use-package flycheck-popup-tip)
(use-package flycheck-rust :after (rust-mode))
(use-package go-mode :defer t)
(use-package helm-dash)
(use-package html-to-hiccup)
(use-package js2-mode :defer t)
(use-package json-navigator)
(use-package markdown-preview-eww)
(use-package markdown-preview-mode)
(use-package nav-flash)
(use-package nov)
(use-package parseedn)
(use-package prettier-js)
(use-package racer)
(use-package racket-mode :defer t)
(use-package ranger)
(use-package restart-emacs)
(use-package rjsx-mode)
(use-package rust-mode :defer t)
(use-package slime)
(use-package sqlup-mode)
(use-package tree-mode)
(use-package undo-tree)
(use-package uuid)
(use-package vega-view)
(use-package yasnippet)

(provide 'startup)
